# Optimized Mikrotik Configuration (Final)
# Generated by Jules
#
# INSTRUCTIONS:
# 1. Upload this file to your Router (Files menu).
# 2. Open Terminal.
# 3. Run command: /import optimized_mikrotik.rsc
#
# CHANGES:
# - Active-Active Load Balancing (PCC 11 Streams)
# - Dynamic Sticky (Solves Banking/HTTPS Logouts)
# - Recursive Routing (Soft Failover)
# - Automated Cleanup of old conflicts

# --- 1. CLEANUP OLD CONFLICTS ---
# Remove old PCC/Sticky rules to prevent duplicates/conflicts
/ip firewall mangle remove [find comment~"PCC"]
/ip firewall mangle remove [find comment~"Sticky"]
/ip firewall mangle remove [find comment~"Routing"]
/ip firewall mangle remove [find comment~"Output"]
/ip firewall mangle remove [find comment="IN_ISP1"]
/ip firewall mangle remove [find comment="IN_ISP2"]

# --- 2. QOS CAKE ---
/queue type
add kind=cake name=cake-download cake-rtt-scheme=internet on-error={}
add kind=cake name=cake-upload cake-rtt-scheme=internet on-error={}
/queue simple
remove [find name="01_Total_Office_CAKE"]
add name="01_Total_Office_CAKE" target=10.10.10.0/24 max-limit=550M/550M \
    queue=cake-upload/cake-download comment="QoS CAKE - Anti Bufferbloat"

# --- 3. FIREWALL MANGLE ---
/ip firewall mangle
# 0. Bypass Local (Keep existing if present, or add safe guard)
add chain=prerouting action=accept src-address-list=LOKAL dst-address-list=LOKAL comment="0_Bypass_Lokal" place-before=0

# 1. Input/Output Markers (Router Stability)
add chain=input action=mark-connection in-interface=ether1 new-connection-mark=ISP1_conn passthrough=yes comment="IN_ISP1"
add chain=input action=mark-connection in-interface=ether2 new-connection-mark=ISP2_conn passthrough=yes comment="IN_ISP2"
add chain=output action=mark-routing connection-mark=ISP1_conn new-routing-mark=to_ISP1 passthrough=no comment="OUT_ISP1"
add chain=output action=mark-routing connection-mark=ISP2_conn new-routing-mark=to_ISP2 passthrough=no comment="OUT_ISP2"

# 2. Dynamic Sticky - RESTORE (Stability)
add chain=prerouting action=mark-connection new-connection-mark=ISP1_conn src-address-list=Sticky_ISP1 passthrough=yes connection-mark=no-mark comment="Sticky: Keep User on ISP1"
add chain=prerouting action=mark-connection new-connection-mark=ISP2_conn src-address-list=Sticky_ISP2 passthrough=yes connection-mark=no-mark comment="Sticky: Keep User on ISP2"

# 3. PCC Load Balancing (11 Streams)
add chain=prerouting action=mark-connection new-connection-mark=ISP1_conn per-connection-classifier=both-addresses:11/0 connection-mark=no-mark in-interface=bridge-lan passthrough=yes comment="PCC_ISP1_Main"
add chain=prerouting action=mark-connection new-connection-mark=ISP1_conn per-connection-classifier=both-addresses:11/1 connection-mark=no-mark in-interface=bridge-lan passthrough=yes
add chain=prerouting action=mark-connection new-connection-mark=ISP1_conn per-connection-classifier=both-addresses:11/2 connection-mark=no-mark in-interface=bridge-lan passthrough=yes
add chain=prerouting action=mark-connection new-connection-mark=ISP1_conn per-connection-classifier=both-addresses:11/3 connection-mark=no-mark in-interface=bridge-lan passthrough=yes
add chain=prerouting action=mark-connection new-connection-mark=ISP1_conn per-connection-classifier=both-addresses:11/4 connection-mark=no-mark in-interface=bridge-lan passthrough=yes
add chain=prerouting action=mark-connection new-connection-mark=ISP1_conn per-connection-classifier=both-addresses:11/5 connection-mark=no-mark in-interface=bridge-lan passthrough=yes

add chain=prerouting action=mark-connection new-connection-mark=ISP2_conn per-connection-classifier=both-addresses:11/6 connection-mark=no-mark in-interface=bridge-lan passthrough=yes comment="PCC_ISP2_Main"
add chain=prerouting action=mark-connection new-connection-mark=ISP2_conn per-connection-classifier=both-addresses:11/7 connection-mark=no-mark in-interface=bridge-lan passthrough=yes
add chain=prerouting action=mark-connection new-connection-mark=ISP2_conn per-connection-classifier=both-addresses:11/8 connection-mark=no-mark in-interface=bridge-lan passthrough=yes
add chain=prerouting action=mark-connection new-connection-mark=ISP2_conn per-connection-classifier=both-addresses:11/9 connection-mark=no-mark in-interface=bridge-lan passthrough=yes
add chain=prerouting action=mark-connection new-connection-mark=ISP2_conn per-connection-classifier=both-addresses:11/10 connection-mark=no-mark in-interface=bridge-lan passthrough=yes

# 4. Dynamic Sticky - CREATE (Stability)
# Trigger: HTTPS Traffic (Port 443). Lock time: 10 Minutes.
add chain=prerouting action=add-src-to-address-list address-list=Sticky_ISP1 address-list-timeout=10m connection-mark=ISP1_conn protocol=tcp dst-port=443 in-interface=bridge-lan passthrough=yes comment="Sticky: Lock to ISP1"
add chain=prerouting action=add-src-to-address-list address-list=Sticky_ISP2 address-list-timeout=10m connection-mark=ISP2_conn protocol=tcp dst-port=443 in-interface=bridge-lan passthrough=yes comment="Sticky: Lock to ISP2"

# 5. Routing Marks
add chain=prerouting action=mark-routing connection-mark=ISP1_conn new-routing-mark=to_ISP1 passthrough=no in-interface=bridge-lan comment="Route -> ISP1"
add chain=prerouting action=mark-routing connection-mark=ISP2_conn new-routing-mark=to_ISP2 passthrough=no in-interface=bridge-lan comment="Route -> ISP2"


# --- 4. RECURSIVE ROUTING (SOFT FAILOVER) ---
/ip route
# Disable OLD Routes
set [find comment~"Jalur_Main_ISP1"] disabled=yes
set [find comment~"Jalur_Main_ISP2"] disabled=yes
set [find comment~"Jalur_PCC_ISP1"] disabled=yes
set [find comment~"Jalur_PCC_ISP2"] disabled=yes

# Ensure Monitor Targets Exist
add dst-address=4.2.2.2/32 gateway=192.168.1.1 scope=10 comment="Monitor_ISP1" on-error={}
add dst-address=208.67.220.220/32 gateway=192.168.166.1 scope=10 comment="Monitor_ISP2" on-error={}

# Add Recursive Routes (Main Table)
add distance=1 gateway=4.2.2.2 check-gateway=ping target-scope=30 comment="Main_ISP1_Recursive"
add distance=2 gateway=208.67.220.220 check-gateway=ping target-scope=30 comment="Main_ISP2_Recursive"

# Add Recursive Routes (PCC Tables)
# Table to_ISP1
add distance=1 gateway=4.2.2.2 routing-table=to_ISP1 check-gateway=ping target-scope=30 comment="PCC_ISP1_Recursive"
add distance=2 gateway=208.67.220.220 routing-table=to_ISP1 check-gateway=ping target-scope=30 comment="Failover_to_ISP2"
# Table to_ISP2
add distance=1 gateway=208.67.220.220 routing-table=to_ISP2 check-gateway=ping target-scope=30 comment="PCC_ISP2_Recursive"
add distance=2 gateway=4.2.2.2 routing-table=to_ISP2 check-gateway=ping target-scope=30 comment="Failover_to_ISP1"


# --- 5. SCRIPTS & NETWATCH UPDATE ---
/system script
# Update scripts to only FLUSH connections. Do not disable routes.
remove [find name="ISP1_Down"]
remove [find name="ISP2_Down"]
remove [find name="ISP1_Up"]
remove [find name="ISP2_Up"]

add name=Flush_ISP1_Conn source="/ip firewall connection remove [find connection-mark=ISP1_conn]" dont-require-permissions=yes
add name=Flush_ISP2_Conn source="/ip firewall connection remove [find connection-mark=ISP2_conn]" dont-require-permissions=yes

/tool netwatch
# Update Netwatch to call the new scripts
# We use 'set' to modify existing entries by comment
set [find comment="ISP1_Check_A"] down-script="/system script run Flush_ISP1_Conn" up-script=""
set [find comment="ISP1_Check_B"] down-script="/system script run Flush_ISP1_Conn" up-script=""
set [find comment="ISP2_Check_A"] down-script="/system script run Flush_ISP2_Conn" up-script=""
set [find comment="ISP2_Check_B"] down-script="/system script run Flush_ISP2_Conn" up-script=""

# Log success
:log info "OPTIMIZATION COMPLETE: Sticky Rules, Recursive Routes, and Soft Failover installed."
